global:
  scrape_interval:     15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mongo_exporter'

    static_configs:
      - targets: ['hpdb-mongo_exporter:9216']

  - job_name: 'redis_exporter'

    static_configs:
      - targets: ['hpdb-redis_exporter:9121']

  - job_name: 'php_app_exporter'

    metrics_path: '/service/metrics'
    static_configs:
      - targets: ['hpdb-web-api:80']

  - job_name: 'elasticsearch_exporter'

    static_configs:
      - targets: ['hpdb-elastic_exporter:9114']
