version: '3.1'

networks:
  hpdb-network:
    external:
      name: hpdb-network

services:
  web-api:
    container_name: "hpdb-web-api"
    image: nginx
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.template"
      - "./:/var/www/html"
    ports:
      - "9883:80"
    environment:
      - NGINX_HOST=${NGINX_HOST_API}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-api
    networks:
      - hpdb-network
  php-api:
    container_name: "hpdb-php-api"
    image: boryashkin/hpdbru_php-api:latest
    restart: always
    volumes:
      - "./:/var/www/html"
    networks:
      - hpdb-network
  redis:
    image: redis:5.0.5-alpine
    container_name: ${REDIS_HOST}
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - hpdb-network
  mongo:
    image: mongo:4.1.5-xenial
    container_name: ${MONGO_HOST}
    restart: always
    volumes:
      - ./data/mongo:/data/db
    networks:
      - hpdb-network
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: "hpdb-elastic"
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    networks:
      - hpdb-network
  prometheus:
    image: prom/prometheus:latest
    container_name: "hpdb-prometheus"
    volumes:
      - ./docker/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hpdb-network
  mongoexporter:
    image: boryashkin/percona_mongo_exporter:master
    container_name: "hpdb-mongo_exporter"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://${MONGO_HOST}:${MONGO_PORT}
    networks:
      - hpdb-network
  redisexporter:
    image: oliver006/redis_exporter:latest
    container_name: "hpdb-redis_exporter"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://${REDIS_HOST}:6379
    networks:
      - hpdb-network
  grafana:
    image: grafana/grafana:latest
    container_name: "hpdb-grafana"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - hpdb-network
